name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Rename repository directory
      #   run: mv osl. osl

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build application
        run: make -C osl

      - name: Run tests
        run: make -C osl test

      - name: Clean up
        run: make -C osl clean

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Rename repository directory
      #   run: rename osl. osl

      - name: Set up MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-g++
            make

      - name: Add MSYS2 to PATH
        run: |
          echo "C:/msys64/usr/bin" >> $GITHUB_PATH
          echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

      - name: Build application
        run: make -C osl
        shell: msys2 {0}

      - name: Run tests
        run: make -C osl test
        shell: msys2 {0}

      - name: Clean up
        run: make -C osl clean
        shell: msys2 {0}
