name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up MSYS2 environment
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-gcc
          make

    - name: Add MSYS2 to PATH
      run: |
        echo "C:/msys64/usr/bin" >> $GITHUB_PATH
        echo "C:/msys64/mingw64/bin" >> $GITHUB_PATH

    - name: Build application
      run: make
      shell: msys2 {0}
      
    - name: Clean up
      run: make clean
      shell: msys2 {0}
